### ISSUE TITLE
Debating about an official build tool ...

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#123]
Hi,

I can see that their are 3 ways for building :

+ `make`
+ `neph`
+ `docker`

I personnaly using `make` (cause it's easy and I'm lazy).

@tbrand I can see that are building using `neph`

Shouldn't we build using the same thing ?

Behind that, there is the idea of a cross-platform solution -> building `objectif c`, `dot net`, and **else** using the same toolchain / isolation level.

For me `docker` is a good idea, but for **linux** enable tools (no `asp` no `swift` ...).

I suggest we use `Vagrant` (cause there is **OS X**, **Windows** ...).

@tbrand @OvermindDL1 what do you think about that ?

Regards,

**Comment by OvermindDL1** [comment]
I'd probably just use `make` or shell scripts myself in general...?

**Comment by waghanza** [comment]
@OvermindDL1 its what I do but ... I do not run `asp` or `swift` benchmarks ;-)

there is not many solution that could be used to create various (OS) targets

**Comment by OvermindDL1** [comment]
> @OvermindDL1 its what I do but ... I do not run asp or swift benchmarks ;-)

Ditto.  ^.^;

Probably docker that is front-managed by a `make` file or shell script would probably be best.

**Comment by waghanza** [comment]
@OvermindDL1 the problem will be the same ...

`docker` is `linux` specific

**Comment by OvermindDL1** [comment]
> docker is linux specific

Uh... no?  I'm pretty sure it runs on mac, and it *definitely* runs on windows (we are using it on windows at work)...  o.O?

**Comment by waghanza** [comment]
@OvermindDL1 ;-)

sure

`docker` work on **Windows**

but you can not create **Windows** `targets`, can you ?

**Comment by OvermindDL1** [comment]
> but you can not create Windows targets, can you ?

In a VM setup, but then again, screw windows?  ^.^

**Comment by waghanza** [comment]
@OvermindDL1 Not a **windows*** fan either, but as a performance comparison, I think its a mistake too not show `asp` performance ..

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Not a windows* fan either, but as a performance comparison, I think its a mistake too not show asp performance ..

But asp works just fine on linux (we are running an ASP site with the official Microsoft .NET Core on RedHat7 at work)?

**Comment by waghanza** [comment]
@OvermindDL1 I do not know that such language is officially supported by **RedHat** 👍 

However, the idea here is not to debate about language ... but how to build `which_is_the_fastest`

my point is that building, in my point of view, **SHOULD** be *cross-platform* (for the moment cross-os), not just to say that we **COULD** by to be **closest** as real usage ;-).

it could be accurate in the feature to benchmarks **python** and **ruby** on `FreeBSD` for example

**Comment by OvermindDL1** [comment]
> @OvermindDL1 I do not know that such language is officially supported by RedHat +1

Recently added (about a year ago or so).  We converted the front-end website (marketing department uses an ASP horror that we'd prefer not, but eh...) to redhat with it with no issues.
https://developers.redhat.com/topics/dotnet/

**Comment by waghanza** [comment]
:trollface: sorry, I feel your pain ...

**Comment by waghanza** [comment]
to be serious, `docker` **COULD** be a solution ...

if @tbrand and you are OK ;-)

**Comment by tbrand** [comment]
Just for me, I continue to use `neph`. It's very good tool for me. :smile: I can put a patch by myself when new repository has been added.
So if **main** build tools will be moved to `docker`, that's ok. But we cannot remove neph completely.
`make` is very common tools - so the same reason as neph - it is difficult to remove from the project I think.

**Comment by waghanza** [comment]
sure, I don't want to remove something ... taste and flavour, is for each developer

@tbrand I think about **one** tool use to display _official_ results. not a problem for me if you use `neph`  and some others `make`, just for me **docker** could help maintaining because portable ... and what about your time ;-)
