### ISSUE TITLE
Change order in Ranking of frameworks

### ISSUE THREAD

**Issue by faustinoaq** [tbrand/which_is_the_fastest#13]
![image4493](https://cloud.githubusercontent.com/assets/3067335/25642853/0abaef58-2f62-11e7-8913-e8c1577edfc9.png)

Kemal is the 4th after route.cr, nickel.rs and Iron
![f64326f8-2f39-11e7-998d-565b02f5bc49](https://cloud.githubusercontent.com/assets/3067335/25642925/76c962e2-2f62-11e7-8b05-f487f631bdb2.png)

**Comment by tbrand** [comment]
Oops, thanks! will fix this ASAP :)

**Comment by tbrand** [comment]
I've fix this. will close the issue.
https://github.com/tbrand/which_is_the_fastest/commit/22da7eff18eef240d72e924d80d96924dd8035d2
