### ISSUE TITLE
Flask server be crashed during the benchmarking

### ISSUE THREAD

**Issue by tbrand** [tbrand/which_is_the_fastest#134]
This command will be crashed.

```bash
./bin/benchmarker flask
```

However, executing it manually is success.

server
```bash
./bin/server_python_flask
```

client
```bash
curl localhost:3000
curl localhost:3000/user/3
curl -XPOST localhost:3000/user
```

**Comment by waghanza** [comment]
@tbrand Not on my side ...

I've noticed some timeout with built-in servers (what ever languages).

I suggest running flask with a **production-ready** `server` such as **gunicorn** (as I used in **django**)

**Comment by waghanza** [comment]
@tbrand still having this on **master** ?

**Comment by tbrand** [comment]
Reopen this if it's still happen. (Sorry I don't have a time to do it now :pray:)
