### ISSUE TITLE
Using gunicorn for Flask

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#144]
Hi,

[Flask](http://flask.pocoo.org) use [werzheug](http://werkzeug.pocoo.org) as built-in web server.

Werzheug does not intend to be **production-ready** => http://werkzeug.pocoo.org/docs/0.14/serving/.

I suggest to use [Gunicorn](http://gunicorn.org/) to assume serving, since **production-ready**.

Regards,

**Comment by tbrand** [comment]
@waghanza can be closed?
