### ISSUE TITLE
Node app are running on development

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#153]
Hi,

`Node` apps are running on **development** mode, the default.

I don't know what differences are in **production** vs **development** mode (on `node `).

@lukeed How can I set **production** mode is `polka` ?

Regards,

**Comment by lukeed** [comment]
There's no difference, at least not in Polka. Neither app in this suite does anything differently according to the environment, so not sure why this matters. But typically you prepend the script with the value going want.

```
NODE_ENV=production node server
```

**Comment by waghanza** [comment]
ok, thanks
I'll keep set this `env` var in order not to miss it, fr other `node` frameworks => #154
