### ISSUE TITLE
How to run benchmarker locally?

### ISSUE THREAD

**Issue by georgeu2000** [tbrand/which_is_the_fastest#159]
On OSX, the following succeeds:

`make client benchmarker roda`

but when I run `bin/benchmarker roda`, it just hangs:

```
Last update: 2018-03-06
``
OS: Darwin (version: 17.4.0, arch: x86_64)
CPU Cores: 4
``
Benchmark running ...
```

Are there any other steps required?

**Comment by waghanza** [comment]
This works ....
~~~sh
make client benchmarker roda
bin/benchmarker roda
~~~
In fact, it's not hanging :stuck_out_tongue: it is just a background process running
check process list, for example
~~~sh
ps aux | grep roda
~~~

I close this comment, but feel free to re-open if needed

**Comment by georgeu2000** [comment]
Thank you, I see that it worked. Why doesn't it use CPU? Wouldn't it make many requests?

**Comment by waghanza** [comment]
I mean not specialized in `roda` ***routing** so ...

+ For the CPU

> I just can say that `puma` is used :stuck_out_tongue_winking_eye: but not configured, I'll need to standardize all configuration so as all languages / frameworks use the same resources

+ For the request number

See https://github.com/tbrand/which_is_the_fastest#the-rule

**Comment by georgeu2000** [comment]
OK, thanks for the explanation.
