### ISSUE TITLE
Rack Routing Benchmark does not seem correct

### ISSUE THREAD

**Issue by georgeu2000** [tbrand/which_is_the_fastest#161]
Should be 20% slower than Roda, but is approx. 800% slower on README.

![image](https://user-images.githubusercontent.com/794632/37059813-3d22825c-2143-11e8-92f8-9a9dd4c0f797.png)

**Comment by waghanza** [comment]
Hi @georgeu2000,

How is created your result ?

I'm not sure about the difference between `roda` and `rack-routing` ;-) but there is a lot of points here :

* Which hardware are you using (thread / os / cores) ?
* Are you running from **master** ?
* Which ruby version (which engine `mri`, `jruby`, `cruby` ...) ?
* ...

Regards,

PS : Results could differ a lot depending on process ;-), for example, **plug** **SHOULD** also be fastest that **phoenix** (in `elixir world)

**Comment by georgeu2000** [comment]
@waghanza - I am using a 2017 Macbook Pro. I did `bin/benchmarker roda rack-routing`. Yes I am running from master. MRI `ruby 2.4.3p205`.

Rack Routing is similar to Roda and Sinatra. It should run about as fast as Roda (which it does on my machine) and 2X-3X faster than Sinatra. There is no reason for it to take as long as Rails, which is 8X too slow.

How are the results generated? I assumed it was with `bin/benchmarker`, but maybe that is not correct...

I think it needs to be generated again.

**Comment by georgeu2000** [comment]
I ran it again and got similar results:

```
~/projects/which_is_the_fastest > bin/benchmarker ruby
Last update: 2018-03-12
``
OS: Darwin (version: 17.4.0, arch: x86_64)
CPU Cores: 4
``
Benchmark running ...
Done. <- rails
Done. <- sinatra
Done. <- roda
Done. <- rack-routing

### Ranking (Framework)

1. [roda](https://github.com/jeremyevans/roda) (ruby)
2. [rack-routing](https://github.com/georgeu2000/rack-routing) (ruby)
3. [sinatra](https://github.com/sinatra/sinatra) (ruby)
4. [rails](https://github.com/rails/rails) (ruby)

### Ranking (Language)

1. ruby ([roda](https://github.com/jeremyevans/roda))

### All frameworks

| Language (Runtime)        | Framework (Middleware)    |       Max [sec] |       Min [sec] |       Ave [sec] |
|---------------------------|---------------------------|-----------------|-----------------|-----------------|
| ruby                      | rails                     |      125.416754 |      116.677648 |      119.733618 |
| ruby                      | sinatra                   |       36.379258 |       34.146462 |       35.375841 |
| ruby                      | roda                      |       12.331125 |       12.057775 |       12.132294 |
| ruby                      | rack-routing              |       16.616053 |       15.572159 |       16.064085 |
```

**Comment by OvermindDL1** [comment]
> PS : Results could differ a lot depending on process ;-), for example, plug SHOULD also be fastest that phoenix (in elixir world), but it is NOT the case on the README.md

Yep, the current testing machine is a desktop, which is not what such things would normally be run on, especially since it's a mac desktop, which is even more rare that they would not be run on.  ^.^;

**Comment by waghanza** [comment]
@georgeu2000 are you running from **master** ?

**Comment by georgeu2000** [comment]
@waghanza - Yes, I updated to `8ceeb2`and got the same results:

```
bin/benchmarker roda rack-routing sinatra
Last update: 2018-03-12
``
OS: Darwin (version: 17.4.0, arch: x86_64)
CPU Cores: 4
threads: 5, requests: 10000
``
Benchmark running ...
Done. <- sinatra
Done. <- roda
Done. <- rack-routing

### Ranking (Framework)

1. [roda](https://github.com/jeremyevans/roda) (ruby)
2. [rack-routing](https://github.com/iAmPlus/rack-routing) (ruby)
3. [sinatra](https://github.com/sinatra/sinatra) (ruby)

### Ranking (Language)

1. ruby ([roda](https://github.com/jeremyevans/roda))

### All frameworks

| Language (Runtime)        | Framework (Middleware)    |       Max [sec] |       Min [sec] |       Ave [sec] |
|---------------------------|---------------------------|-----------------|-----------------|-----------------|
| ruby                      | sinatra                   |       36.937729 |       35.681776 |       36.391956 |
| ruby                      | roda                      |       13.352440 |       11.910231 |       12.339293 |
| ruby                      | rack-routing              |       15.375852 |       14.838942 |       15.032817 |
~/projects/which_is_the_fastest > git log
commit 8ceeb294cfede6a700c0c8febf6643ebeb2676f9 (HEAD
```

**Comment by waghanza** [comment]
@georgeu2000 I understand your point, but there is some discussion point about your concern :

1. How can you say than `rack-routing` **SHOULD** be 20% less performing than `roda` ?
2. Is the code behind using the same thing (same appserver, same env) or as closest as it can
3. Is this very relevant to test on a `mac` ? as @OvermindDL1 said it's a desktop machine
4. As your result say, `rack-routing` **IS** _13,16%_ slower than `roda`

**Comment by georgeu2000** [comment]
1. How can you say than rack-routing SHOULD be 20% less performing than roda ?
Because it uses similar technology and my benchmarks show that.

2. Is the code behind using the same thing (same appserver, same env) or as closest as it can
Yes, same.

3. Is this very relevant to test on a mac ? as @OvermindDL1 said it's a desktop machine
Yes. It should not make a difference, at least between Ruby servers. It doesn't matter if it is a desktop or laptop

4. As your result say, rack-routing IS 13,16% slower than roda
Yes, rack-routing is about 15% slower than roda.

Can you verify the benchmark? It seems to me that if you run it again you should get different results.

**Comment by waghanza** [comment]
@georgeu2000 
> Yes, rack-routing is about 15% slower than roda.
So, what's the issue ?

The result in `README.md` will be updated regularly, please see #165, the result are updated by @tbrand

**Comment by OvermindDL1** [comment]
>  Yes. It should not make a difference, at least between Ruby servers. It doesn't matter if it is a desktop or laptop

It *ABSOLUTELY* would make a different between desktop/laptops and servers though.  Server OS's are designed for backend through-put performance where desktop/laptops are optimized for front-end responsiveness, each of which entirely change many things about how such benchmarks would run.
