### ISSUE TITLE
Debating about benchmarking tool

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#172]
Hi,

I want to open a discussion about the benchmarking tool.  

This tool is _actually_ **internal**. The purpose of this discussion is not to say that actual tool is bad, but how it could be better :stuck_out_tongue:

There is plenty of tools for benchmark / HTTP load test :

+ https://github.com/JoeDog/siege
+ JMeter / ab, from `Apache`
+ https://github.com/rakyll/hey, from `Google`
+ http://curl-loader.sourceforge.net/
+ https://github.com/gatling/gatling
+ https://github.com/sdogruyol/cryload
+ ...

I think this tool **COULD** give us more flexibility if is a separate project (espacially `cryload` :heart: since it is in `crystal`).

What do you think ?

Regards,

**Comment by OvermindDL1** [comment]
I like using `wrk` personally as it gives a lot of statistical information (it's what I used in my statistics tested thread).

**Comment by OvermindDL1** [comment]
Please see #173 where it shows just how utterly *bad* cryload and hey are, and how the rest don't really get anywhere near `wrk`'s capabilities, throughput, and reporting accuracy.

I.E. `wrk` should be chosen.

**Comment by OvermindDL1** [comment]
And copied from other thread about the client in this repo directly:

Did some testing with the crystal benchmarker built in to this repo, it cannot even get close to saturating the C++/Rust/Go servers and it's capping out at ~100% CPU Usage as well, which also implies it has a GIL and/or is otherwise useless at benchmarking, so the built in client is useless.

* client ~100% CPU Usage : cpp_evht ~103% CPU Usage (better than even cryload!  o.O)
* client ~93% CPU Usage : crystal_router_cr ~100% (The server got capped out so the client couldn't even hit 'its' own max speed...)
* client ~113% CPU Usage : rust_iron ~118%
* client ~119% CPU Usage : go_fasthttprouter ~115%

And the results were:

> > ╰─➤  bin/benchmarker cpp router_cr iron fasthttprouter                                                         > [8/1850]
> Last update: 2018-04-03
> ```
> OS: Linux (version: 4.15.0-041500-generic, arch: x86_64)
> CPU Cores: 16
> threads: 17, requests: 10000
> ```
> Benchmark running ...
> Done. <- router_cr
> Done. <- fasthttprouter
> Done. <- iron
> Done. <- evhtp
> 
> ### Ranking (Framework)
> 
> 1. [iron](https://github.com/iron/iron) (rust)
> 2. [evhtp](https://github.com/criticalstack/libevhtp) (cpp)
> 3. [router_cr](https://github.com/tbrand/router.cr) (crystal)
> 4. [fasthttprouter](https://github.com/buaazp/fasthttprouter) (go)
> 
> ### Ranking (Language)
> 
> 1. rust ([iron](https://github.com/iron/iron))
> 2. cpp ([evhtp](https://github.com/criticalstack/libevhtp))
> 3. crystal ([router_cr](https://github.com/tbrand/router.cr))
> 4. go ([fasthttprouter](https://github.com/buaazp/fasthttprouter))
> 
> ### All frameworks
> 
> | Language (Runtime)        | Framework (Middleware)    |       Max [sec] |       Min [sec] |       Ave [sec] |
> |---------------------------|---------------------------|-----------------|-----------------|-----------------|
> | crystal                   | router_cr                 |        9.271305 |        7.377060 |        8.109800 |
> | go                        | fasthttprouter            |       11.308970 |       10.808372 |       11.063619 |
> | rust                      | iron                      |        7.676771 |        5.964357 |        6.809752 |
> | cpp                       | evhtp                     |        7.443327 |        6.498350 |        6.914891 |


So this definitely shows that the built-in client is pretty abysmal as well.  If anything it's measuring the CPU Kernel Context Switching costs more than it is benchmarking the servers...  It cannot saturate more than a single core, and thus is artificially limiting *most* servers, this is pretty ***bad*** and makes the results reported in the Readme entirely false...  Was this never checked for before?!  o.O

**Comment by OvermindDL1** [comment]
My simple wrk-wrapper would be *significantly* better than the current benchmarker used as it is actually accurate unlike the current benchmarker, perhaps it should be put in 'for now' until a proper `wrk` wrapper is made?

**Comment by OvermindDL1** [comment]
In comparison to the currently included benchmarker/client, my stats script reports this for the same input:

╰─➤  ../stats.exs -w 1 -d 3 cpp router_cr iron fasthttprouter
Total Cores: 16
Concurrent Connections: 1000

Processing servers:
* bin/server_cpp_evhtp
* bin/server_crystal_router_cr
* bin/server_rust_iron
* bin/server_go_fasthttprouter

... snip setup and running output ...

| Path | URL | Errors | Total Requests Count | Total Requests/s | Total Requests Throughput | Total Throughput/s Avg | Req/s Stdev | Req/s Max | Req/s +/- | Latency Avg | Latency Stdev | Latency Max | Latency +/- | 50% | 75% | 90%
 | 99% |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- 
| :--- | :--- |
| bin/server_cpp_evhtp | http://127.0.0.1:3000/ | 0 | 2156046 | 703568.41 | 131.59MB | 42.94MB | 90.13k | 26.83k | 126.
24k | 65.83% | 2.07ms | 3.06ms | 40.06ms | 88.71% | 724.00us | 2.19ms | 5.74ms | 14.26ms |
| bin/server_cpp_evhtp | http://127.0.0.1:3000/user | 0 | 2039529 | 667643.16 | 124.48MB | 40.75MB | 85.26k | 23.88k | 
127.95k | 57.50% | 2.02ms | 2.74ms | 33.78ms | 87.95% | 759.00us | 2.31ms | 5.45ms | 13.00ms |
| bin/server_cpp_evhtp | http://127.0.0.1:3000/user/0 | 0 | 2021280 | 659912.61 | 181.20MB | 59.16MB | 84.43k | 23.17k 
| 121.01k | 60.83% | 2.18ms | 3.34ms | 217.02ms | 88.75% | 771.00us | 2.32ms | 6.02ms | 14.66ms |
| bin/server_crystal_router_cr | http://127.0.0.1:3000/ | 0 | 225563 | 73779.68 | 13.34MB | 4.36MB | 9.44k | 785.16 | 11.23k | 80.83% | 13.09ms | 3.24ms | 26.12ms | 75.23% | 11.12ms | 16.31ms | 16.97ms | 22.85ms |
| bin/server_crystal_router_cr | http://127.0.0.1:3000/user | 0 | 182351 | 60207.92 | 10.78MB | 3.56MB | 7.63k | 525.8$ | 8.76k | 72.92% | 16.29ms | 3.99ms | 27.99ms | 73.06% | 16.11ms | 19.21ms | 20.35ms | 26.26ms |
| bin/server_crystal_router_cr | http://127.0.0.1:3000/user/0 | 0 | 206894 | 68487.47 | 18.15MB | 6.01MB | 8.66k | 0.9$k | 10.08k | 75.83% | 13.90ms | 3.18ms | 30.39ms | 84.41% | 12.56ms | 16.52ms | 19.05ms | 25.28ms |
| bin/server_go_fasthttprouter | http://127.0.0.1:3000/ | 0 | 1602555 | 518915.4 | 142.13MB | 46.02MB | 66.77k | 14.96$ | 107.77k | 64.58% | 1.80ms | 3.58ms | 203.50ms | 96.29% | 1.14ms | 2.01ms | 3.63ms | 7.72ms |
| bin/server_go_fasthttprouter | http://127.0.0.1:3000/user | 0 | 1510736 | 496216.31 | 133.99MB | 44.01MB | 63.00k | $3.36k | 106.57k | 72.92% | 2.00ms | 5.04ms | 206.40ms | 97.90% | 1.28ms | 2.14ms | 3.61ms | 9.04ms |
| bin/server_go_fasthttprouter | http://127.0.0.1:3000/user/0 | 0 | 1436093 | 467731.85 | 224.61MB | 73.15MB | 59.82k $ 12.22k | 98.13k | 68.75% | 2.29ms | 7.19ms | 207.41ms | 98.89% | 1.32ms | 2.31ms | 4.07ms | 9.93ms |
| bin/server_rust_iron | http://127.0.0.1:3000/ | 0 | 1173985 | 383845.77 | 83.97MB | 27.45MB | 56.17k | 30.85k | 112.$8k | 60.95% | 454.90us | 8.18ms | 535.23ms | 99.90% | 206.00us | 324.00us | 432.00us | 1.10ms |
| bin/server_rust_iron | http://127.0.0.1:3000/user | 0 | 1119812 | 368037.9 | 80.10MB | 26.32MB | 74.91k | 32.86k | 1$9.27k | 72.67% | 268.12us | 343.24us | 20.08ms | 97.39% | 223.00us | 304.00us | 421.00us | 0.87ms |
| bin/server_rust_iron | http://127.0.0.1:3000/user/0 | 0 | 1036645 | 337967.06 | 129.51MB | 42.22MB | 49.65k | 29.19k | 108.00k | 70.48% | 328.18us | 273.45us | 23.72ms | 94.44% | 323.00us | 412.00us | 508.00us | 0.88ms |

# Rankings

## Ranking by Average Requests per second:
1. 677041 req/sec : bin/server_cpp_evhtp
2. 494287 req/sec : bin/server_go_fasthttprouter
3. 363283 req/sec : bin/server_rust_iron
4. 67491 req/sec : bin/server_crystal_router_cr


So not only does the built-in benchmark take like *7* entire **seconds** just to push through a measly 10k requests, this thing is pushing through 677 *thousand* requests *per* second while also reporting significantly more accurate information.

**Comment by waghanza** [comment]
@OvermindDL1 seems clear :+1: 
@tbrand any suggestions ?

if OK, I'll update the _codebase_ to use  `wrk` instead of our internal tool
