### ISSUE TITLE
Updating results

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#175]
Hi,

On `readme` => https://github.com/tbrand/which_is_the_fastest#current-target-frameworks-middlewares all frameworks are not listed, for example https://github.com/spider-gazelle/spider-gazelle (newly introduced :stuck_out_tongue:).

@tbrand How result are updated ?

We can probably use [crystal markdown built-in](https://crystal-lang.org/api/0.24.1/Markdown/Renderer.html) to update the results.

Regards,

**Comment by OvermindDL1** [comment]
> How result are updated ?

He runs them on his desktop computer using the crystal benchmarker which was recently shown to be *entirely* inaccurate in benchmarking servers and is better at benchmarking context switch's when a server is 'fast enough' (most).  ^.^;

This definitely needs to be fixed.  :-)

> We can probably use crystal markdown built-in to update the results.

These tests already use nodejs, why not use the official commonmark parser in GF-markdown mode?

**Comment by waghanza** [comment]
+ For running, I suggest to run on some clouds, AWS should be enough. 

You have to do some concession between **flexibility** and **performance**. My idea is to run **from** a _CI_ **to** a cloud. It could ensure a high level of automation ;-)

+ As this project is in crystal, why mixing languages ?

**Comment by tbrand** [comment]
OK, running on cloud is acceptable. Then we have to remove the Objective-C framework by default.

**Comment by waghanza** [comment]
@tbrand not necessarily :stuck_out_tongue: 
**objective c** could compile on linux https://gist.github.com/nicerobot/5652802

but to be honest, it will be hard / not a priority for me

**Comment by OvermindDL1** [comment]
@tbrand At least until a full wrk tool is supplied can I can you my wrk script for now?

**Comment by tbrand** [comment]
Done.

**Comment by tbrand** [comment]
@OvermindDL1 Please integrate it if you want to use that tool.

**Comment by OvermindDL1** [comment]
I'll try to PR it today, it's very basic and only does what is needed, but it is easy to cleanup if wanted.  I should add a `--help` argument to it first probably...
