### ISSUE TITLE
Fail building rocket

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#177]
Hi,

I have an issue **compiling** `rocket` code => https://github.com/tbrand/which_is_the_fastest/tree/master/rust/rocket

I have

~~~rust
  |
1 | #![feature(plugin_registrar, rustc_private, quote)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

The following warnings were emitted during compilation:

warning: Pear was unable to check rustc compatibility.
warning: Build may fail due to incompatible rustc version.

error: Could not compile `pear_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:152: rocket] Error 101
~~~

@SergioBenitez an idea ?

Regards,

PS : I am running on `rust` **1.24.0**

**Comment by SergioBenitez** [comment]
You need the latest Rust nightly to compile Rocket.

**Comment by waghanza** [comment]
@SergioBenitez does it mean that `rocket` will always use _nightly_ releases (not build on _stable_) ? or is this for the actual release ?

**Comment by OvermindDL1** [comment]
'Most' Rust projects require Rust Nightly.  Rust Nightly has a lot of features that are extremely useful but not quite 'finished' enough for release (though still super-useful), so if you use Rust, you almost always need nightly, for production releases or not.
