### ISSUE TITLE
Using --no-debug on crystal ?

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#178]
Hi,

Using `--no-debug` **flag** on `crystal` compilation, reduce binaries size :

| Framework | without --no-debug | with --no-debug |
| -------------- | ------------------------ | -------------------- |
| Amber | 2.3M | 1.2M |
| Kemal | 1.5M | 820K |
| Lucky | 1.6M | 848K |
| Raze | 1.4M | 748K |
| Router.cr | 1.2M | 652K |
| Spider-Gazelle | 1.4M | 788K |

However, using this flag increase compilation duration.

@stakach @tbrand @samueleaton @paulcsmith @sdogruyol @faustinoaq What do you think ?

Regards,

**Comment by faustinoaq** [comment]
@waghanza I agree :+1: 

BTW, Actually, Amber is the most heavy binary because we embed all LICENSES into it to follow MIT compliance. See: https://github.com/elorest/compiled_license by @elorest :wink: 

> But if you distribute binaries, the license text (typically) gets compiled away, therefore you are no longer fulfilling the single condition in the license. What you need to do is include the license with your binary distributions, maybe as a text file, or embedded in the program's about dialog. For most distribution channels, there's some way of including the source code license(s)

Ref: https://opensource.stackexchange.com/questions/4058/what-is-the-point-of-including-the-mit-copyright-text-if-you-use-someones-code

**Comment by paulcsmith** [comment]
I think the size difference is not much of a concern. I’d rather have debug info if something goes wrong so that it’s easier to see what piece of code caused an issue. I’d rather have that than save a few megs of space personally

**Comment by faustinoaq** [comment]
Hi @paulcsmith, I also think `--no-debug` isn't very useful on development, but hey, this is a benchmark, so, a lightweight binary is generated faster and without extra info, BTW, we already using this flag on [Techempower Benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/crystal/setup.sh#L7)  :wink:

 I think if you really want to debug crystal code, you should use the `--debug` flag :+1:

**Comment by waghanza** [comment]
+ with
~~~
real	0m58.937s
user	0m8.815s
sys	0m14.506s
~~~
+ without
~~~
real	0m58.846s
user	0m8.811s
sys	0m14.335s
~~~

On a **production-ready** stack, the main advantage for me is the size decrease means a bandwidth decrease (bandwidth when deploying on many servers).

For me using `--no-debug` **SOULD** be used ?

@tbrand @OvermindDL1 What do you think ?

**Comment by paulcsmith** [comment]
On production, I would not use --no-debug because your stack traces are nearly indecipherable. It makes debugging runtime error super hard. But for benchmarking it may be fine since there isn't a lot that can go wrong with such simple endpoints

**Comment by OvermindDL1** [comment]
As it's a benchmark I'm all for `--no-debug`.  :-)

**Comment by samueleaton** [comment]
Agree. benchmarks can use `--no-debug`.

**Comment by waghanza** [comment]
Thanks for you returns. `--no-debug` is now one on the **master** `branch`
