### ISSUE TITLE
Keeping .pins files in Swift

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#179]
Hi,

I can see that installed packages are outdated on `Swift`.

I am not aware on any best-practices in this language.

**SHOULD** we keep or remove 

* Package.pins
* Package.resolved

in a **benchmarks** perspective ?

@kjessup @tanner0101 @kiliankoe  What do you think ?

Regards,

**Comment by tanner0101** [comment]
Run `swift package update` to resolve the latest dependencies. You'll usually want to test to make sure everything is still working as expected after doing that, so I think keeping the `Package.resolved` file is smart. That's what SPM recommends as well. Basically it makes upgrading opt-in.

**Comment by kiliankoe** [comment]
Also `Package.pins` can be deleted. Swift updates have made that obsolete and `Package.resolved` is now used instead.

**Comment by waghanza** [comment]
@tanner0101 @kiliankoe thanks for your answers. I will `drop` `Package.pins` from this repository
