### ISSUE TITLE
CPP evhtp removal

### ISSUE THREAD

**Issue by OvermindDL1** [tbrand/which_is_the_fastest#181]
@tbrand Why was the CPP evhtp test removed?  I see this in the latest release:

> I've removed the evhtp(cpp) from the targets.
> Every frameworks or middlewares have to have a feature of parsing path parameter.
> 
> tbrand/which_is_the_fastest/pull/173/files#diff-e3b4a7c3d038b88c4d74d11f403fe216R24
> 
> But the above implementation is not that one.
> That's not a feature but an implementation of cpp.

Libevhtp *does* have that capability (via globbing, regex, path matching, also supports vhosts, middlewares, hooks, etc... etc... it is a full framework, not a low level TCP library), I just didn't use it because I was lazy and I did not see where it was required to use that functionality.  If you wanted it added then you could have asked me to change those couple of lines but removing not just the CPP but the entire commit outright not via a rollback commit but via another commit that contains *other* data makes it difficult to re-add it again without rolling back the latest commit.

**Comment by OvermindDL1** [comment]
@tbrand In addition, the results show that you are still using the single-core crystal benchmarker, I'm guessing to artificially inflate the crystal results on the benchmark because even the devs of Crystal themselves in IRC stated *not* to use Crystal as a benchmarker because it will cause every server tested here to be throttled, thus showing better the servers that don't have any locking even though they would perform worse in every real-world test.

At this point I cannot help but think that this repo is not interested in accurate testing as well, which saddens me...

**Comment by waghanza** [comment]
I close since issue since last merge, re-enable [evhtp](https://github.com/criticalstack/libevhtp)
