### ISSUE TITLE
mofuw failed to compile

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#185]
Hi,

When trying to compile `mofuw`, I have

~~~nim
Error: '$addr(buf[r])' cannot be assigned to
~~~

@2vg What does `bufSize` mean ?

Regards,

**Comment by 2vg** [comment]
@waghanza sorry, but it has been fixed just now.

**Comment by 2vg** [comment]
Also, bufSize is the size of the temporary buffer at the time of receiving the request.
This size is difficult to adjust, but 512 is sufficient if it is about benchmark.
(Because it is not assumed that a large size request will come)

**Comment by waghanza** [comment]
@2vg so quick

it is working, now https://travis-ci.org/waghanza/which_is_the_fastest

**Comment by 2vg** [comment]
Why not close?
Do you have any other problems?
