### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by kiliankoe** [tbrand/which_is_the_fastest#20]
What's your stance on including swift frameworks here? The downside I have in mind is that the list of supported platforms is still rather limited. Things should however work on macOS and Ubuntu at the least, since those are officially supported.

The most popular (bigger) frameworks are

- [Vapor](https://vapor.codes)
- [Perfect](https://www.perfect.org)
- [Kitura](http://www.kitura.io)

**Comment by tbrand** [comment]
> What's your stance on including swift frameworks here?

Of course, every frameworks and middlewares are target.
Only an limitation is that these frameworks or middlewares have to have routing and parsing path parameters features.

> Things should however work on macOS and Ubuntu at the least

For me, I run this benchmark on mac. :smile:

**Comment by kiliankoe** [comment]
Awesome! I might be sending you a few PRs then in the coming days 😜 Unless of course someone else is faster^^

**Comment by tbrand** [comment]
I'm looking forward. 💯
