### ISSUE TITLE
Router.cr version

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#201]
Hi @tbrand,

We use `route.cr` `0.2.2`.

However, on shard.yml, I can found that version is `0.1.13`.

In which version is `router.cr` ?

Regards,

**Comment by tbrand** [comment]
I've pushed the v0.2.3 which is tagged and shard.yml is udpated.
Could you use it?

**Comment by waghanza** [comment]
sure

I find it easier / more understandable if the **version** is the same number of the **tag**
