### ISSUE TITLE
Next update

### ISSUE THREAD

**Issue by tbrand** [tbrand/which_is_the_fastest#203]
Now we successfully migrate for using docker.
So everyone who has docker env can update the result.

@waghanza will you?

**Comment by waghanza** [comment]
@tbrand sure, in the next days

**Comment by waghanza** [comment]
@OvermindDL1 I intend to update this **benchmarker** to run as well on private servers ;-) but if you mind instead `docker` on you server :stuck_out_tongue:  feel free to use it 

but the `env` va `DOCKER_HOST` is **required**, `docker` **cli** tool could be configured
@see https://docs.docker.com/engine/reference/commandline/cli/#description

**Comment by OvermindDL1** [comment]
Already have docker installed.  :-)

Just make sure all usage is documented in the readme or so would be the best help?

**Comment by OvermindDL1** [comment]
And of course don't use the horribly broken crystal-built benchmarker.  ^.^;

**Comment by waghanza** [comment]
@OvermindDL1 next steps are (for me) :
+ documentation
+ make benchmarker script use wrk

**Comment by waghanza** [comment]
@tbrand If you are OK with that, I'll turn the notation system is a [SemVer](https://semver.org) way.

The purpose of that is to reach 1.x.x (e.g : **stable**) when (at least) :
* running on cloud
* using `wrk`

**Comment by waghanza** [comment]
@tbrand New realease is [here](https://github.com/tbrand/which_is_the_fastest/releases/tag/2018.5.12)

**Comment by tbrand** [comment]
Awesome! Good work! :+1:
