### ISSUE TITLE
Use pm2 runtime for node

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#211]
Hi @thiamsantos,

I can see that `node` is used on `node` benchmarks. Some of `nodejs` folks seems to use `pm2` as **production-ready** runtime.

What do you think of switching to `pm2` ?

Regards,

**Comment by ThiccCat** [comment]
it doesn't change anything besides running bloatware while benchmarking node.js

**Comment by waghanza** [comment]
@ThiccCat I have a significant difference between running on `pm2` and `node`. 

I'm just trying to ask what is commonly used / recommended by the community :stuck_out_tongue:

**Comment by thiamsantos** [comment]
@waghanza `pm2` just automatically run your application on a cluster. It is the recommended way to run node apps. We could use `pm2` to run the clustered version of the node apps, instead of manually implementing the cluster inside of the app.

**Comment by waghanza** [comment]
Thanks @thiamsantos, we use `pm2` as runtime for node, with #212

As far as I understand, `node` is like `rack` and `pm2` is like `puma` ;-) in the **ruby** world
