### ISSUE TITLE
Add hapi (Node)

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#233]
https://github.com/hapijs/hapi

**Comment by armand1m** [comment]
@waghanza great work mate! I see the PR is merged but no docs were added, nor a place in the benchmarks. @waghanza these would be extremely helpful as well =)

**Comment by aichholzer** [comment]
Isn't Hapi like the slowest framework around?

**Comment by armand1m** [comment]
@aichholzer that is the point =)

**Comment by waghanza** [comment]
@armand1m Thanks. Good catch ;-) 

due to intense work :stuck_out_tongue: `hapi` has been dropped (unintentionally)

`hapi` will be added to the next release

@aichholzer We will see ... the next release will no be **production-ready**, the next after will (but I do not know when I will have the time to do so)

PS : Some previous results

| Language (Runtime)        | Framework (Middleware)    |    Requests / s |      Throughput |
|---------------------------|---------------------------|----------------:|---------:|
| node                      | fastify                   | 61358.00 | 91.68 MB |
| node                      | polka                     | 52718.00 | 78.61 MB |
| node                      | rayo                      | 47574.00 | 71.10 MB |
| node                      | koa                       | 36394.00 | 76.90 MB |
| node                      | express                   | 33598.00 | 82.17 MB |
| node                      | restify                   | 34149.00 | 59.80 MB |
| node                      | hapi                      | 29352.00 | 54.91 MB |

**Comment by aichholzer** [comment]
How did Fastify get almost 10K req/s ahead of the rest? - Does not seem to be realistic.

**Comment by aichholzer** [comment]
If you are running on a multi-core server, then you should enable [`@rayo/storm`](https://github.com/GetRayo/rayo.js/tree/master/packages/storm) in the latest version of [`rayo`](https://github.com/GetRayo/rayo.js).

It will increase it's performance (and throughput) by almost 200% percent, hence blowing the socks off the other contenders, although it will probably not be a fair competition... 🙈

**Comment by waghanza** [comment]
@aichholzer :stuck_out_tongue: I'm sure you'll be impatient to compete ^^

Feel free to `PR` usage for [`@rayo/storm`](https://github.com/GetRayo/rayo.js/tree/master/packages/storm). I'll be glad to merge

**Comment by aichholzer** [comment]
PM2 will run on multi-cores if enabled and if the server supports it. I will try to get a PR across. Still curious on Fastify's performance gains.

**Comment by waghanza** [comment]
@aichholzer sending those result was a (gentle) provocation :stuck_out_tongue:.

Above results are **garbage** / **draft**

**Comment by aichholzer** [comment]
🤣 
Well done!
