### ISSUE TITLE
Add rayos.js (Node)

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#237]
Hi @aichholzer,

It could be intersting to add https://github.com/GetRayo/rayo.js to this benchmarking project ?

Regards,

**Comment by aichholzer** [comment]
Thank you @waghanza -Will submit a PR.

**Comment by aichholzer** [comment]
@waghanza -Interesting, in none of my tests has `fastify` ever been faster and my results are also usually faster than `polka`.

**Comment by waghanza** [comment]
I think I have been tout enthusiastic. Results are wrong. I'll fix it

**Comment by aichholzer** [comment]
⚡️ Looking forward to that.
Thank you.

**Comment by aichholzer** [comment]
⚡️ Yeah, that look like my sorts of results.
Thank you.

**Comment by aichholzer** [comment]
Hello @waghanza -A couple of questions;

- [ ] Will you be pushing those results into `master` [here](https://github.com/tbrand/which_is_the_fastest) anytime soon?
- [ ] Looking at [your results](https://github.com/waghanza/which_is_the_fastest/blob/wrk/README.md) and [these](https://github.com/tbrand/which_is_the_fastest) ones, there are quite some differences. For example `router.cr` goes from 1st place to 19th place, which does not look right. Also, I don't think any Nodejs framework would be faster than `japronto` (although I am flattered to see `rayo` above it 😉)
- [ ] Finally, I don't think [this](https://github.com/waghanza/which_is_the_fastest/blob/wrk/README.md#ranking-language) list is ordered quite alright, unless the order is not based on performance.

Looking forward to your thoughts.

**Comment by waghanza** [comment]
@aichholzer Could yo re-integrate your code ? (I did not why the disappeared -> mis-merge, or something)
+ I'll release results this week
+ The (actual on **master**) results are **wrong**, calculated with a built-in sieger (I'm working on a version to use `wrk`)
+ The ranking order only take count of req/s (and calculated from a workstation - not ideal)

**Comment by aichholzer** [comment]
😢

**Comment by waghanza** [comment]
I re-enabled [Rayo](https://github.com/GetRayo/rayo.js) in #246
