### ISSUE TITLE
node framework with combination of uws server will be rock 

### ISSUE THREAD

**Issue by hbakhtiyor** [tbrand/which_is_the_fastest#24]
would be nice to check the [benchmarks](https://github.com/hbakhtiyor/node-frameworks-benchmark) and use it for your benchmarks

**Comment by tbrand** [comment]
I don't understand. Could you tell me the detail?

**Comment by hbakhtiyor** [comment]
currently you use express for node, would be nice to add with combination of [uws](https://github.com/uWebSockets/uWebSockets) which i did

**Comment by tbrand** [comment]
Seems good! Any tunings under the regulation are welcome. :smile:
But I myself don't focus on any frameworks, so please send me PRs who want to tuning them.:+1:
