### ISSUE TITLE
Results for single and multiple threads

### ISSUE THREAD

**Issue by j8r** [tbrand/which_is_the_fastest#250]
The results used to be on a single core, and now are on 8 cores. This doesn't really represent all environments.
On microservice architectures with e.g. Docker, it's really common to have multiple single-threaded container instances.

**Comment by waghanza** [comment]
Results are run on some `workstations` (we are plan to change this) in order to have a **real-world** environment

**Comment by OvermindDL1** [comment]
Docker single-threaded?  Not that I've ever seen?  o.O

**Comment by waghanza** [comment]
@j8r I close this issue (since we plan to run on cloud and probably also ecs)
