### ISSUE TITLE
Fail to get mofuw IP

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#267]
Hi @2vg,

`mofuw` is failing on https://travis-ci.com/tbrand/which_is_the_fastest/jobs/130808330

Regards,

**Comment by 2vg** [comment]
Hello, I made destructive changes to mofuw, so it may be because of it.
Since I submitted a new pull request, please test it there.

**Comment by waghanza** [comment]
I see https://github.com/tbrand/which_is_the_fastest/pull/268

I'll merge it after CI
