### ISSUE TITLE
Automatically update the result

### ISSUE THREAD

**Issue by tbrand** [tbrand/which_is_the_fastest#27]

**Comment by kelvinst** [comment]
That would be awesome :)

Or even, running the benchmark on different CI's, just because...

**Comment by michalmuskala** [comment]
I don't think running on a CI would provide any meaningful data. Those are probably virtualised machines sharing CPU with other things - the data would be completely unreliable.

**Comment by tbrand** [comment]
@michalmuskala That's pretty true...

**Comment by waghanza** [comment]
@michalmuskala Some CI tools are base on containairizarion
