### ISSUE TITLE
Fix jester

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#296]
Hi,

`jester` is failing. A mid (short) workaround is to use a specific commit as in https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Nim/jester/techempower.nimble

`jester` target the next `nim` release, hoppefully comming in August :-)

Regards,

**Comment by dom96** [comment]
because that image only offers the latest stable Nim version AFAIK
