### ISSUE TITLE
Bandwith usage on vibora

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#310]
Hi @frnkvieira,

`vibora` is **awesome** :tada:  https://github.com/tbrand/which_is_the_fastest#results

However, the implementation here consume a lot of bandwidth.

Is there any best-practices for decreasing bandwidth ?

In case of using `vibora` on mobile networks bandwidth matters a lot ;-).

Regards,

**Comment by OvermindDL1** [comment]
Look at it's headers, that would be why it's eating more bandwidth.

**Comment by waghanza** [comment]
@OvermindDL1`curl -v http://0.0.0.0:3000/user/0` gives me
~~~
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 3000 (#0)
> GET /user/0 HTTP/1.1
> Host: 0.0.0.0:3000
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 1
< Date: Mon, 30 Jul 2018 20:01:47 GMT
< 
* Connection #0 to host 0.0.0.0 left intact
~~~

**Comment by OvermindDL1** [comment]
That's barely anything then...  Are you sure the bandwidth usage *per* request is high?

**Comment by waghanza** [comment]
no, global one

**Comment by OvermindDL1** [comment]
Global is fine as long as the request count is high.  Throughput per request is the request size.

**Comment by OvermindDL1** [comment]
> perhaps to be clearer, it could be useful to display also throughput per request

+1, each framework will likely have a different default size, and if you are trying to get the most requests pumped out then reducing it in each frameworks own way when appropriate is useful.

**Comment by waghanza** [comment]
I let you tune the `C++ ` implementations then :stuck_out_tongue_winking_eye:

**Comment by OvermindDL1** [comment]
Poke me at times to do so to remind me, crunch period at work currently so I'm not able to do much else.  ^.^;

**Comment by waghanza** [comment]
@OvermindDL1 better now :stuck_out_tongue: 

| Language (Runtime)        | Framework (Middleware)    |    Requests / s | Throughput per request |      Throughput |
|---------------------------|---------------------------|----------------:|---------:|---------:|
| python                    | vibora                    | 150610.67 | 75.21 B | 170.88 MB |
