### ISSUE TITLE
Is Sanic running with all workers?

### ISSUE THREAD

**Issue by mrkaspa** [tbrand/which_is_the_fastest#44]
By default runs with 1, we can set as many cores we have

```python
app.run(host="0.0.0.0", port=port, workers=os.cpu_count())
```

**Comment by tbrand** [comment]
Any tunings are welcome!! I'll try this, thanks!

**Comment by mrkaspa** [comment]
I made the fix https://github.com/tbrand/which_is_the_fastest/pull/45

**Comment by tbrand** [comment]
Thanks!!!
