### ISSUE TITLE
Replace the client with a proper seiger

### ISSUE THREAD

**Issue by OvermindDL1** [tbrand/which_is_the_fastest#59]
The current client is not able to saturate servers properly (at least locally here with 6 native cores), which causes the results of the fastest servers to not be accurate in relation to each other, it should perhaps be replaced with a proper http siege engine such as `wrk` or `httpsiege`, which also have a lot more configuration and testing options.  `wrk` tends to be more common.  Thoughts?  Would a PR be accepted for this and if so what siege engine should be used?

If one is swapped I'd probably propose using a siege engine(s) that are capable of:

* HTTP1.0
* HTTP1.1
* HTTP2.0
* Websocket

Perhaps also testing:

* Response data for consistency
* Headers so we can test setting headers
* HTTP Streaming
* Error rates:
  * Test proper error handling for invalid requests.
  * Test how the webserver fails when it is saturated, such as delaying responses, dropping connections, falling over in death, etc...
* Etc...

Any other ideas?  Any of these should be left out?

Saving results to the git repo might be useful as well, organized by system the results were run on, at what git version, at what date, etc..., perhaps with scripts to generate result graphs automatically.

In addition it could use proper servers for testing, I have a 6-native-core Linux server that I can donate for such testing.  I might be able to spool up sessions on a 24-core server but it is not 'empty' by any stretch so it would skew results compared to the empty 6-core server.  I have a 4-native core (8-HT) Linux server on the same network interlink that I can siege 'from' to the 6-core server as well to test it over an network as well so the siege process itself does not interfere with the actual servers.

**Comment by waghanza** [comment]
I've just open #223 to use `wrk`

**Comment by OvermindDL1** [comment]
Awesome, and for note I have 8 native core with 16 hyperthreads under low/no use that I can test with now too.  ^.^

**Comment by waghanza** [comment]
#223 was merged
