### ISSUE TITLE
Testing a go router

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#6]
Hello,

Thanks for this **amazing** benchmark.

Can you add a `routing` library in `go`, such as https://github.com/karlseguin/router.

`router.cr` is compared to `kemal` but `kemal` is a **framework** an `router.cr` a **routing library**

**Comment by tbrand** [comment]
Thanks for your comment!
I agree to add such a middleware! But I'm suspicious that the router is the de facto standard for gophers. Is there any other famous routers for Golang? If it's not, I will add karlseguin/router.

**Comment by waghanza** [comment]
In fact, I'm not a **gopher**ist 😜, but could it be **interesting** to test a `famous` and `well-spreaded` router as [mux](https://github.com/gorilla/mux)

**Comment by tbrand** [comment]
I'm not good at Go as well :smile:
OK, I will try to add https://github.com/gorilla/mux .

**Comment by tbrand** [comment]
I've added gorilla/mux! The result will be updated soon.
Thanks for your suggestion:smile:
