### ISSUE TITLE
Would anyone be a contributor?

### ISSUE THREAD

**Issue by tbrand** [tbrand/which_is_the_fastest#63]
I'm busy for other tasks recent days...
So it's hard to maintain this repository anymore.

Give me a comment who can
1. build all frameworks included in this repository
2. by neph

Of course I will back up when I can.
Thanks!

**Comment by OvermindDL1** [comment]
I've both been able to build and run all servers here (though some run dreadfully slow... (ruby)) and I just built neph successfully.  My time is often fairly short as well but I'd be willing to help as I can.  Delegate to others first though.  :-)

**Comment by tbrand** [comment]
@OvermindDL1 
I know you did help me continuously:heart:
I would like you to invite as a contributor!
Thanks!!

**Comment by OvermindDL1** [comment]
Heh, no others popping up?  I think it'd be fun to grow this into a variety of tests too.  ^.^
