### ISSUE TITLE
Drop repo's 'crystallang' and 'crystal-language' topics

### ISSUE THREAD

**Issue by matiasgarciaisaia** [tbrand/which_is_the_fastest#7]
The Crystal community has somewhat decided to [use `crystal` as the language's topic](https://github.com/search?utf8=✓&q=topic%3Acrystal&type=Repositories).

To avoid fragmentation in the community, please drop `crystallang` and `crystal-language` topics, that only have ~12 or ~28 repositories at the moment. We're sticking to `crystal`, instead.

Any contributor can change it from the repo's homepage.

See crystal-lang/crystal#4241 for more context.

Thank you very much :)

**Comment by tbrand** [comment]
DONE.
