### ISSUE TITLE
Invalid benchmarks

### ISSUE THREAD

**Issue by esemplastic** [tbrand/which_is_the_fastest#71]
Hello, I've seen your try to make benchmark tests on different type of routers and web frameworks (which is not the same thing , is like comparing apples with cars, but this is your own choice) but this is not a fair benchmark because some web frameworks running from dynamic ipv6/or ipv4 address and some others from static ipv4.

Take for example the the go/gorillamux  vs iris vs echo,
go/gorillamux uses `regexp` while iris uses one of the fastest algorithms for routing (it's well known for that), iris is battle-tested on different type of web applications already, however your benchmark results shows gorilla mux overperform iris and echo, this is not possible because **golang's regexp is the slowest method** see here http://benchmarksgame.alioth.debian.org/u64q/regexredux.html

EDIT:

Also on Iris you store the path parameter before send it to the client while in echo you send it without storing it to variable, please fix that too.

Thank you!

**Comment by krypton97** [comment]
@esemplastic I didn't commit any updates to the iris code and after that open that issue. I wanna see where I did those modification. Also @hiveminded, "attack on iris"?? I hope you're kidding here..

**Comment by pjmtdw** [comment]
If changing listening address from `:3000` to `localhost:3000` really affects the performance, which is done in [this commit](https://github.com/tbrand/which_is_the_fastest/pull/72/files), I think the [this code](https://github.com/tbrand/which_is_the_fastest/blob/master/go/echo/main.go) should also be changed to `localhost:3000`

**Comment by kalicki** [comment]
Duplicate... Close?!
