### ISSUE TITLE
Add Amber framework

### ISSUE THREAD

**Issue by ansarizafar** [tbrand/which_is_the_fastest#74]
Please add [https://amberframework.org](https://amberframework.org) to the benchmark.

**Comment by tbrand** [comment]
Will do it.
PR is very welcome though.

**Comment by kalicki** [comment]
PR =) ping to... @veelenga @drujensen @faustinoaq

**Comment by kalicki** [comment]
Ping @elorest

**Comment by veelenga** [comment]
I can try. But afaik the benchmark has be run on the same machine others tests were run, no?

**Comment by kalicki** [comment]
That would be perfect! But as far as I understand the ‘neph’ tries to create a unique environment for testing. I think the @tbrand can explain better, but a percentage of error can occur

**Comment by kalicki** [comment]
Also, I think @tbrand valid PR on your machine

**Comment by elorest** [comment]
I'll try to look into that soon. I'm super swamped at work right now.

**Comment by kalicki** [comment]
Hey @elorest and @veelenga, news? We look forward to your help =) 
Thanks!

**Comment by waghanza** [comment]
I've add **amber** in  `PR` #112

**Comment by waghanza** [comment]
@tbrand Can we close ?

**Comment by tbrand** [comment]
Good job!
