### ISSUE TITLE
Add gin (Golang)

### ISSUE THREAD

**Issue by tbrand** [tbrand/which_is_the_fastest#81]
https://github.com/gin-gonic/gin

**Comment by kalicki** [comment]
Ping to... @manucorporat, @javierprovecho, @appleboy

**Comment by appleboy** [comment]
maybe I can send the pull request for gin.

**Comment by tbrand** [comment]
@amscotti has been added Gin, Thanks!! :tada:
https://github.com/tbrand/which_is_the_fastest/pull/96
