### ISSUE TITLE
Missing Iris from go list but shown on benchmarks - is that possible?

### ISSUE THREAD

**Issue by esemplastic** [tbrand/which_is_the_fastest#83]
Hey @tbrand sorry for the noise but I've just tried to reproduce your results and I couldn't because you show results of some libraries that are not even exist in this repository, how you do that?

Let me explain,

I've seen Iris in the list of your benchmark list but was [never ran](https://github.com/tbrand/which_is_the_fastest/blob/3ef78e76b405b9af1b23f61a9375cc23ee4fad79/Makefile#L73) because you didn't include that go framework in the go list, so why you include iris in your benchmark results?

The following link proofs that I'm saying to you people: https://github.com/tbrand/which_is_the_fastest/blob/3ef78e76b405b9af1b23f61a9375cc23ee4fad79/Makefile#L73 November of 2017 -branch=master). **It proofs that [iris](https://iris-go.com) was never included in the benchmarks, so the results we see at the homepage of this project cannot be trusted**. shows your current master branch. 

Please fix that immediately and update your results, keep note that we all know that go's regexp are slower than trie algorithms so fix iris and echo (both iris and echo are faster than gorilla mux, iris should be shown as the fastest one, among the frameworks built on top of the standard net/http package).

My previous issue about invalid benchmarks: https://github.com/tbrand/which_is_the_fastest/issues/71

**Comment by esemplastic** [comment]
I made my local changes to add iris to the benchmarks and the results are:

![newbenchmarks](https://user-images.githubusercontent.com/26099364/32709938-0a4de5ba-c83d-11e7-9a9d-ce95ba78ab19.png)

I'll add a PR soon which fixes a lot of issues when people try to build this software (because of bugs like llvm), review it and re-run your benchmarks on your own machine to verify and update the readme page, ok @tbrand ?

**Comment by tbrand** [comment]
I always building whole frameworks or middleware by using `neph`.
neph.yaml includes Iris at [here](https://github.com/tbrand/which_is_the_fastest/blob/master/neph.yml#L100).

But missing from Makefile is my bad, could you give me the PR?
Thanks!

**Comment by waghanza** [comment]
@tbrand Re-enabled in `PR` #124

**Comment by waghanza** [comment]
@esemplastic I close. Feel free to re-open, if you still have issue with **master**
