### ISSUE TITLE
Add Lucky (Crystal)

### ISSUE THREAD

**Issue by kalicki** [tbrand/which_is_the_fastest#84]
This web framework It's interesting to analyze...

http://github.com/luckyframework by @paulcsmith

**Comment by paulcsmith** [comment]
Thanks for the ping! I'm working on a PR for this now :)

**Comment by kalicki** [comment]
News?

**Comment by paulcsmith** [comment]
I've been sick and on vacation :P So not the best week for getting things done. I did get pretty far though. Hoping to have something soon

**Comment by kalicki** [comment]
Hey @paulcsmith, news? We look forward to your help =)

**Comment by paulcsmith** [comment]
@kalicki PR open at #100 :D

**Comment by paulcsmith** [comment]
I haven't done any perf tuning on Lucky so I'm not sure how it will fare, but it is using Crystal so I'm sure it will be at somewhat quick

**Comment by kalicki** [comment]
With the end result we can abstract the demand for improvements. Good Job! Thanks.

**Comment by kalicki** [comment]
Open issue? For fix error in json
https://github.com/tbrand/which_is_the_fastest/releases/tag/v1.2.3

**Comment by paulcsmith** [comment]
@tbrand Could you provide some more info on what went wrong when compiling/running Lucky? It's hard to say for sure but I'm guessing something went wrong when building it. Maybe you need to install the Lucky CLI first? https://luckyframework.org/guides/installing/#install-lucky

**Comment by tbrand** [comment]
Oh I see. will try it.

**Comment by waghanza** [comment]
[Lucky](https://luckyframework.org) failed to compile

@paulcsmith empty manifest seems to be the root cause

@tbrand I've fixed that #116

**Comment by paulcsmith** [comment]
The empty manifest is part of the problem, but I worry it is not a long-term solution. The `bin/setup` script for Lucky should install the packages and generate an empty manifest automatically. So I'm guessing something failed while running `bin/setup`. If the Lucki CLI is not installed then the lucky db commands and the command for generating the assets would fail, meaning there would be no manifest

I think the best solution would be to see if installing the CLI fixes the issue. I suppose adding a blank manifest won't hurt but may not be necessary

**Comment by waghanza** [comment]
ok

@paulcsmith `crystal` **clear**

@tbrand I think adding an empty `manifest` is ok for our purpose, even it's not ideal

**Comment by waghanza** [comment]
@tbrand Can we close ?

**Comment by tbrand** [comment]
Yup
