### ISSUE TITLE
Framework request: hyper 0.11 (with Tokio)

### ISSUE THREAD

**Issue by steveklabnik** [tbrand/which_is_the_fastest#9]
I'm filing an issue rather than sending a PR here because hyper 0.11 isn't _quite_ out, but is close.

Currently, all the Rust frameworks are based on synchronous I/O. Hyper 0.11 will include [Tokio](https://tokio.rs/) support, which should put up even better numbers.

I'm happy to actually send a PR, either if "using hyper master" is okay, or once it's released.

**Comment by tbrand** [comment]
Great!
Of course "using hyper master" is **ok** since I will upgrade every frameworks at sometimes. :smile:

**Comment by tbrand** [comment]
As you can see [here](https://github.com/tbrand/which_is_the_fastest/blob/master/Makefile#L57)

**Comment by tbrand** [comment]
Please see here why I close this.
https://github.com/tbrand/which_is_the_fastest/pull/12

Sorry:cry:
